### ISSUE TITLE
generate Auftragsdatei

### ISSUE THREAD

**Issue by michaelkamphausen** [coop-care/paid#15]

**Comment by westnordost** [comment]
The documentation for Auftragsdatei for "Sonstige Leistungserbringer" seems to be missing completely.

**Comment by westnordost** [comment]
I've looked at docs for another Leistungserbringer-group, like doctors:

https://gkv-datenaustausch.de/media/dokumente/leistungserbringer_1/aerzte/technische_anlagen___aktuell/20190910_TA1_18.pdf

It's written slightly differently, but the documentation for the Auftragsdatei is identical otherwise.
**Minus** one field at the end: For Pflege, it should be the Leistungsart. I am assuming that a similar setup should be done for the Sonstige Leistungserbringer. But as said, the documentation is missing completely.

**Comment by michaelkamphausen** [comment]
I don't remember how I found these, but during a previous research I found these files:
https://gkv-datenaustausch.de/media/dokumente/standards_und_normen/technische_spezifikationen/Anlage_2_-_Auftragsdatei.pdf
https://gkv-datenaustausch.de/media/dokumente/leistungserbringer_1/pflege/technische_anlagen_aktuell_2/20070125_TA1_ANH1.pdf

**Comment by westnordost** [comment]
Thanks! So the second one is the one I based my implementation on so far. The first one I haven't seen yet.
